apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: plogger
  name: plogger
spec:
  containers:
  - image: findpritish/plogger:1.8
    name: plogger
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
